### ISSUE TITLE
Build.jl to make the libtet.so

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/TetGen.jl#1]
I started to create the build.jl. However didn't yet get hang of it.

**Comment by TeroFrondelius** [comment]
Partly done. Now the libtet.so is build in deps/builds/libtet folder.
Problem remaining is:

``` julia
===============================[ ERROR: TetGen ]================================

LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency libtet
while loading /home/tero/.julia/v0.4/TetGen/deps/build.jl, in expression starting on line 23

================================================================================
```

I think this is just a learning issue.

**Comment by TeroFrondelius** [comment]
Now it works! https://github.com/JuliaFEM/TetGen.jl/commit/c96d59418987262ee3ddc1fbaef83cfe73775e5d

@ovainola either `cd TetGen/deps`  and run `julia build.jl` or in REPL `julia > Pkg.build("TetGen")` then libtet.so is in deps/urs/lib and tetgen.h is in deps/usr/include

**Comment by ovainola** [comment]
Nice one! I've been debugging with makefile for a hour. I've added a small wrapper into /dev, which wraps main function. I guess we could change couple of lines of code where we include .so with Libdl, much more elegant way

**Comment by TeroFrondelius** [comment]
Yes I did already. That can be found in src/TetGen.jl
