### ISSUE TITLE
TetGen with BinaryProvider

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaFEM/TetGen.jl#5]
I created a binaryprovider build for Tetgen in https://github.com/JuliaGeometry/Tetgen.jl. 
Builds are passing on all tested platforms and it seems like a good way to move forward.
It also seems reasonable to me to have TetGen live in JuliaGeometry, since there is nothing FEM specific about TetGen!
Do we want to move development to JuliaGeometry?
As long as Cxx is not working that easily, I was also thinking to just use tetgen via pipes, which is not as nice, but works pretty allright! ;)

**Comment by TeroFrondelius** [comment]
Everything works for me. It would be nice to have tetmeshing algorithm for adaptive FEM. Will it be in JuliaGeometry or JuliaFEM or working through pipes doesn't matter to me.

**Comment by SimonDanisch** [comment]
Tetgen is 100% wrapped now in https://github.com/JuliaGeometry/Tetgen.jl via C/C++, so performance should be optimal :) Should we change this repository to JuliaGeometry/Tetgen.jl, since it's also officially registered?

**Comment by TeroFrondelius** [comment]
@SimonDanisch sounds good. What should I do to make it happen?

**Comment by SimonDanisch** [comment]
I guess update the readme to point to JuliaGeometry/Tetgen.jl and archive this repository ;)

**Comment by TeroFrondelius** [comment]
See https://github.com/JuliaGeometry/Tetgen.jl
